import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { getTools } from '@/lib/get-tools';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tools = getTools();
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen bg-black text-white">
          <Sidebar tools={tools} />
          <main className="flex-1 p-12 bg-gradient-to-br from-gray-900 to-black overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
